{
	"version": 1702333250,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/background.png",
		"images/background_template.png",
		"images/ground-sheet0.png",
		"images/hero-sheet0.png",
		"images/hero-sheet1.png",
		"images/hero-sheet2.png",
		"images/sprite-sheet0.png",
		"images/spikes-sheet0.png",
		"images/respawn-sheet0.png",
		"images/jumpthru-sheet0.png",
		"images/spring-sheet0.png",
		"images/bird-sheet0.png",
		"images/boundary-sheet0.png",
		"images/bullet-sheet0.png",
		"images/bullet-sheet1.png",
		"images/gem-sheet0.png",
		"images/iconcaroot-sheet0.png",
		"images/iconlife-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/tiledbackground2.png",
		"images/background_2.png",
		"images/background_template_2.png",
		"images/boar-sheet0.png",
		"images/boar-sheet1.png",
		"images/bear-sheet0.png",
		"images/carrot-sheet0.png",
		"images/background3.png",
		"images/background_template3.png",
		"images/boss-sheet0.png",
		"images/boss-sheet1.png",
		"images/boss-sheet2.png",
		"images/boss-sheet3.png",
		"images/tiledbackground.png",
		"images/tile-sheet0.png",
		"images/tile-sheet1.png",
		"images/skel-sheet0.png",
		"images/cactus-sheet0.png",
		"images/cactus2-sheet0.png",
		"images/arrow-sheet0.png",
		"images/box-sheet0.png",
		"images/object-sheet0.png",
		"images/tree-sheet0.png",
		"images/tiledbackground3.png",
		"images/rock-sheet0.png",
		"images/sign2-sheet0.png",
		"images/tiledbackground4.png",
		"images/stone-sheet0.png",
		"images/bush1-sheet0.png",
		"images/bg.png",
		"images/fire-sheet0.png",
		"images/fire-sheet1.png",
		"images/spike1-sheet0.png",
		"media/collect gem.m4a",
		"media/collect gem.ogg",
		"media/enemyhit.m4a",
		"media/enemyhit.ogg",
		"media/collect key.m4a",
		"media/collect key.ogg",
		"media/hit.m4a",
		"media/hit.ogg",
		"media/jingle lose.m4a",
		"media/jingle lose.ogg",
		"media/jingle win.m4a",
		"media/jingle win.ogg",
		"media/mattoglseby - 1.m4a",
		"media/mattoglseby - 1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}